[dask]
workers = 1

[simulation]
pyretis_inp = "retis.rst"
internal = false
steps = 10
seed = 0
save_loc = "./"
load_dir = "trajs"

[output]
backup = "backup"
store_paths = true
screen = 1
pattern = true
data_dir = "./"
delete_old = true
